inherit_from:
 - .rubocop_airbnb.yml

#Rails用に最適化
Rails:
  Enabled: true

#文字数上限
LineLength:
  Max: 160

#解析除外ファイル
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'